### ISSUE TITLE
OpenStudio asking to set path to DView(Mac)

### ISSUE THREAD

**Issue by dylanpath** [NREL/wex#107]
Hi there,
I just installed openstudio and DView for a uni project and i'm trying to open my simulation results, but open studio keeps asking for the path to DView, no matter how many times I set it.
MacOS 10.14.4
<img width="893" alt="Screen Shot 2020-07-19 at 10 16 50 am" src="https://user-images.githubusercontent.com/68486023/87864212-03e1b100-c9a9-11ea-8c09-d6cf4d050c8c.png">

Am I doing something wrong?

**Comment by MatthewSteen** [comment]
@dylanpath this is more of question for UnmetHours.com so please close this bug report if the below solves it.

If you're using the OSApp v1.0+, then DView is no longer installed with the app due to the recent split from the SDK. So, you'll need to install it separately from the releases here.

See the Application release notes...https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.0.0

Specifically the __Note__ about PAT and DView.

**Comment by dylanpath** [comment]
@MatthewSteen I have DView downloaded as a seperate application as you have recommended, but it seems to be an issue of linking it to Open Studio. I'll try posting on UnmetHours. Thanks for your help.

**Comment by MatthewSteen** [comment]
@dylanpath I see, that does sound like a bug. Have you checked the other repos? This one sounds similar...

https://github.com/openstudiocoalition/OpenStudioApplication/issues/96

**Comment by dylanpath** [comment]
I have found a solution for this problem, incase anyone comes across it. When you set the path to DView on Mac, it sets the path for the Dview.app. So to fix the problem, firstly set the path to the Dview app, then add "/Contents/MacOS/DView" to the end of the path selection before clicking ok. Then, navigate to the results tab in Open Studio and you should now be able to open your results through Dview.
