### ISSUE TITLE
DView should not try to convert some units (e.g. hours)

### ISSUE THREAD

**Issue by eringold** [NREL/wex#69]
DView complains when asked to convert some units (like hours), with one of the following popup windows per variable: 
![image](https://user-images.githubusercontent.com/10799524/37662686-373bea2e-2c1d-11e8-87d9-1547d5497624.png)
Suggest DView skip this error for units with no SI/IP distinction.

**Comment by nickdiorio** [comment]
Hi @JShultz89 , we haven't had the bandwidth to investigate this yet, I'll bump it to the top of the priority list.

**Comment by jmarrec** [comment]
+1 Also got stuck in a semi-endless loop.

**Comment by nickdiorio** [comment]
Hi all, I'm not able to reproduce using my test file (attached).
[test.zip](https://github.com/NREL/wex/files/2704735/test.zip)

Can you please post a data file that is displaying this behavior and any other details required to reproduce the error?

**Comment by eringold** [comment]
@nickdiorio the test file you linked is a csv, for which DView doesn't ask to convert units (I think it only does for a [SQL file](https://github.com/NREL/wex/blob/a655e4ec7e570271401dea76c4f809099381a138/src/dview/dvfilereader.cpp#L998)), so it won't show the error. 

I'll email you directly an energyplus output SQL file that exhibits the error.

**Comment by nickdiorio** [comment]
This results from:

0. User selects to convert units when prompted
1. Implementation loops over input variables and attempts to convert based on specified list of units
2. An error message is generated when a unit is detected that the converter does not know about.  I.e, there is no implicit understanding within DView of what units should or should not be converted beyond a list of units that have been defined.

The alternative would be to silently fail and possibly result in unexpected behavior.  Instead of this, I'd recommend simply adding the units to the list of known units and conversions as I did for hours here: https://github.com/NREL/wex/commit/4cbe231a15f0fb9fe1ddffab34cc91ad9ba0a777 

I've created a new DView release with that fix in it, please try it out here: https://github.com/NREL/wex/releases/tag/v1.2.0
