### ISSUE TITLE
.exe file for LK script

### ISSUE THREAD

**Issue by Mo11068** [NREL/wex#86]
Is that possible to create a .exe file for a script written in LK?

Thanks,

**Comment by nickdiorio** [comment]
@sjanzou , can you chime in here?

@Mo11068 , there is not a way presently to compile a lk script to an executable, but I could see how that could be a useful feature.

**Comment by janinefreeman** [comment]
I think that most often, users who are looking to create executable files with SAM functionality use the System Advisor Model software development kit (https://sam.nrel.gov/node/69515) to create their executables using different scripting languages that support executable creation. Otherwise, people looking to share analyses that they have performed using the scripting language can also create a "macro" feature within SAM for people to interact with the LK script without seeing the code.
